In [ ]:
# 2d lists: list of lists
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # 3x3 matrix
for row in a:
    for col in row:
        print(col, end=' ')
    print()

In [ ]:
# print 2nd row:
print(a[1])
# get number 6
print(a[1][2])
# slicing: same as 1d list
print(a[1:3])
print(a[1])
print(a[1:2])

In [2]:
student_grades = [['John', 7.5], ['Mary', 9.0], ['Bob', 6.0], ['Alice', 8.0], ['Mike', 4.0],
                  ['Anna', 10.0], ['Tom', 5.0], ['Peter', 3.5], ['Jane', 9.5], ['Jack', 6.5]]

In [8]:
# Print distinction students who have grade >= 8.0
for row in student_grades:
    if row[1] >= 8.0:
        print(f'Name: {row[0]}, grade: {row[1]}')

Name: Mary, grade: 9.0
Name: Alice, grade: 8.0
Name: Anna, grade: 10.0
Name: Jane, grade: 9.5


In [3]:
# Count how many passed students (grade >= 4.0)
count = 0
for row in student_grades:
    if row[1] >= 4.0:
        count += 1
print('Number of passed students:', count)

Number of passed students: 9


In [10]:
# length of rows can be different
a = [[],
     [1],
     [2, 3],
     [4, 5, 6]]
print(a, len(a))
print(a[3][2])
print(a[2][2]) # error

[[], [1], [2, 3], [4, 5, 6]] 4
6


IndexError: list index out of range

In [12]:
# Exercise
import random as rd
# Create 2d list 5x5 of random integers
a = []
for i in range(5):
    a.append(rd.sample(range(1, 100), 5))
print(a)

[[75, 18, 46, 82, 7], [79, 66, 82, 83, 43], [36, 65, 4, 30, 66], [85, 95, 51, 52, 27], [38, 82, 4, 24, 39]]


In [19]:
# Get 3 middle rows in as many ways as you can
print(a[1:4], a[1:-1], a[-4: -1], a[-4:4], sep='\n')
# Get 2 last rows in as many ways as you can
print(a[3:5], a[3:], a[-2:], a[-2:5], sep='\n')
# Enter n from keyboard, get max, min of nth row and print them (hint: using function max, min)
n = int(input('Enter n: '))
print(f'Max of a[{n}]: {max(a[n])}, min of a[{n}]: {min(a[n])}')
# Enter n from keyboard, get sum of nth row and print it (hint: using function sum)
print(f'Sum of a[{n}]: {sum(a[n])}')
# Enter n from keyboard, sort nth row and print it (hint: using function sorted)
print(f'Sorted a[{n}]: {sorted(a[n])}')


[[79, 66, 82, 83, 43], [36, 65, 4, 30, 66], [85, 95, 51, 52, 27]]
[[79, 66, 82, 83, 43], [36, 65, 4, 30, 66], [85, 95, 51, 52, 27]]
[[79, 66, 82, 83, 43], [36, 65, 4, 30, 66], [85, 95, 51, 52, 27]]
[[79, 66, 82, 83, 43], [36, 65, 4, 30, 66], [85, 95, 51, 52, 27]]
[[85, 95, 51, 52, 27], [38, 82, 4, 24, 39]]
[[85, 95, 51, 52, 27], [38, 82, 4, 24, 39]]
[[85, 95, 51, 52, 27], [38, 82, 4, 24, 39]]
[[85, 95, 51, 52, 27], [38, 82, 4, 24, 39]]
Max of a[3]: 95, min of a[3]: 27
Sum of a[3]: 310
Sorted a[3]: [27, 51, 52, 85, 95]


In [21]:
import numpy as np
# create array from list
a = [1, 2, 3]
b = np.array(a)
print(a, type(a))
print(b, type(b))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [33]:
# create array from arange function (similar range function)
a = np.arange(10)
print(a)
a = np.arange(1, 10, 2)
print(a)
a = np.arange(0, 1, 0.1)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [35]:
# create array from linspace(start, end, n) function
a = np.linspace(0, 9, 9)
print(a)

[0.    1.125 2.25  3.375 4.5   5.625 6.75  7.875 9.   ]


In [37]:
# create array from logspace(start, end, n) function
a = np.logspace(0, 10, 11, base=2, dtype=int)
print(a)

[   1    2    4    8   16   32   64  128  256  512 1024]


In [42]:
# create array from 50 - 100, step 5
a = np.arange(50, 101, 5)
print(a)
# create 15 numbers from 2 to 5
a = np.linspace(2, 5, 15)
print(a)
# create these numbers: 3, 9, 27, 81, 243, 729, 2187, 6561, 19683, 59049
a = np.logspace(1, 10, 10, base=3, dtype=int)
print(a)

[ 50  55  60  65  70  75  80  85  90  95 100]
[2.         2.21428571 2.42857143 2.64285714 2.85714286 3.07142857
 3.28571429 3.5        3.71428571 3.92857143 4.14285714 4.35714286
 4.57142857 4.78571429 5.        ]
[    3     9    27    81   243   729  2187  6561 19683 59049]


In [44]:
# create arrays of zeros, ones
zeros = np.zeros(10)
print(zeros)
ones = np.ones((3, 3))
print(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [48]:
# Array operators: +, -, *, /, %, //, ** with number
a = np.random.randint(10, 100, 5)
print(a)
print(a + 10)
print(a - 10)
print(a * 10)
print(a / 10)
print(a % 10)
print(a // 10)
print(a ** 2)

[29 66 45 82 84]
[39 76 55 92 94]
[19 56 35 72 74]
[290 660 450 820 840]
[2.9 6.6 4.5 8.2 8.4]
[9 6 5 2 4]
[2 6 4 8 8]
[ 841 4356 2025 6724 7056]


In [50]:
# Array operators: +, -, *, /, %, //, ** with array (same size)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a // b)
print(a ** b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[0 0 0]
[  1  32 729]


In [53]:
# Boolean indexing
a = np.random.randint(10, 100, 10)
b = a % 2 == 0
print(a)
print(b)
print(a[b])

[53 71 53 52 73 47 38 76 53 90]
[False False False  True False False  True  True False  True]
[52 38 76 90]


In [56]:
# Find numbers that has the last digit is 3
print(a[a % 10 == 3])
# Find number that has the first digit is 5
print(a[a // 10 == 5])
# Find numbers that has sum of digits > 10
print(a[(a // 10 + a % 10) > 10])

[53 53 73 53]
[53 53 52 53]
[47 38 76]


In [58]:
# 1d Array indexing & slicing: same as list

# 2d Array indexing & slicing
a = np.random.randint(10, 100, (5, 5))
print(a)
# indexing list-style
print(a[2][3])
# indexing array-style
print(a[2, 3])

[[56 31 33 28 84]
 [89 69 30 32 36]
 [27 66 12 80 64]
 [48 26 32 28 14]
 [67 48 68 76 75]]
80
80


In [59]:
# Slice rows:
print(a[1:4])

[[89 69 30 32 36]
 [27 66 12 80 64]
 [48 26 32 28 14]]


In [60]:
# Slice columns:
print(a[:, 1:3])

[[31 33]
 [69 30]
 [66 12]
 [26 32]
 [48 68]]


In [61]:
# Slice both rows and columns:
print(a[1:4, 2:4])

[[30 32]
 [12 80]
 [32 28]]


In [62]:
print(len(a), np.shape(a))

5 (5, 5)


In [66]:
b = a[0]
c = a[0:1, :]
print(b, c)
print(np.shape(b), np.shape(c))
# transpose c
d = c.T
print(d, np.shape(d))

[56 31 33 28 84] [[56 31 33 28 84]]
(5,) (1, 5)
[[56]
 [31]
 [33]
 [28]
 [84]] (5, 1)
