In [7]:
f = open('hello.py', 'r')
content = f.readlines()
print(content)

for line in content:
    print(line.strip())
#f.close()

["print('Hello Python')\n", "a = int(input('Enter a: '))\n", 'print(a)']
print('Hello Python')
a = int(input('Enter a: '))
print(a)


In [9]:
with open('hello.py', 'r') as f:
    content = f.readlines()
    print(content)

["print('Hello Python')\n", "a = int(input('Enter a: '))\n", 'print(a)']


In [10]:
# TODO: read agencies.txt, find all agencies that has Authority in name.
with open('Datasets/agencies.txt', 'r') as f:
    content = f.readlines()
    for line in content:
        if 'Authority' in line:
            print(line.strip())

The Triboro Bridge and Tunnel Authority
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [15]:
# read agencies line by line
try: 
    f = open('Datasets/agencies.txt', 'r')
    line = f.readline()
    while line:
        if 'Authority' in line:
            print(line.strip())
        line = f.readline()
    f.close()
except FileNotFoundError:
    print('File not found')

The Triboro Bridge and Tunnel Authority
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [ ]:
# TODO: count number of lines & number of word in agencies.txt

In [16]:
with open('Datasets/agencies.txt', 'r') as f:
    content = f.readlines()
    print('Number of lines: ', len(content))
    count = 0
    for line in content:
        count += len(line.split()) # count number of words in a line
    print('Number of words: ', count)

Number of lines:  6
Number of words:  30


In [ ]:
# TODO: read & print name, email of authors in authors.txt
# For example: 
# Paul Bakaul    : paul.bakaus@gmail.com
# ERichard Worth : rdworth@gmail.com

with open('Datasets/authors.txt', 'r') as f:
    for i in range(3):
        next(f) # skip 3 first lines
    line = f.readline()
    while line:
        name, email = line.split('<')
        name = name.strip() 
        email = email.strip()[:-1]
        if '@' in email:
            print(f'{name:20} : {email}')
        line = f.readline()


In [4]:
# Read falling.txt, store data into 3 lists: times, heights, uncertainties
with open('Datasets/falling.txt', 'r') as f:
    times = []
    heights = []
    uncertainties = []
    lines = f.readlines()[5:] # read all lines & skip 5 first lines
    for line in lines:
        _, t, h, u = line.split()
        times.append(float(t))
        heights.append(float(h))
        uncertainties.append(float(u))

print('Times: ', times)
print('Heights: ', heights)
print('Uncertainties: ', uncertainties)
    

Times:  [0.0, 0.5, 0.7]
Heights:  [180.0, 185.0, 192.0]
Uncertainties:  [3.5, 4.5, 5.2]


In [6]:
import numpy as np
times, heights, uncertainties = np.loadtxt('Datasets/falling.txt',  # file name
                                            skiprows=5,             # skip 5 first lines
                                            usecols=(1,2,3),        # use columns 1, 2, 3
                                            unpack=True)            # unpack data into 3 arrays
print('Times: ', times)
print('Heights: ', heights)
print('Uncertainties: ', uncertainties)

data = np.loadtxt('Datasets/falling.txt',  # file name
                                            skiprows=5,             # skip 5 first lines
                                            usecols=(1,2,3))
print(data)

Times:  [0.  0.5 0.7]
Heights:  [180. 185. 192.]
Uncertainties:  [3.5 4.5 5.2]
[[  0.  180.    3.5]
 [  0.5 185.    4.5]
 [  0.7 192.    5.2]]


In [9]:
# TODO: Read grades.txt, print Distinction students (average >= 8.0)
data = np.loadtxt('Datasets/grades.txt', skiprows=5, dtype=str)
print('Distinction students:', [row[0] for row in data 
                                    if (float(row[1]) + float(row[2]) + float(row[3]))/3 >= 8.0])

Distinction students: ['Lan', 'Hung']


In [ ]:
for row in data:
    if (float(row[1]) + float(row[2]) + float(row[3]))/3 >= 8.0:
        print(row[0], end=' ')

In [ ]:
names, maths, liters, english = np.loadtxt('Datasets/grades.txt', skiprows=5, dtype=str, unpack=True)
for i in range(len(names)):
    if (float(maths[i]) + float(liters[i]) + float(english[i]))/3 >= 8.0:
        print(names[i], end=' ')

In [ ]:
for name in (row[0] for row in data if (float(row[1]) + float(row[2]) + float(row[3]))/3 >= 8.0):
    print(name, end=' ')

In [13]:
for name in (names[i] for i in range(len(names)) 
                        if (float(maths[i]) + float(liters[i]) + float(english[i]))/3 >= 8.0):
    print(name, end=' ')

Lan Hung 

In [15]:
# Read csv file using numpy.loadtxt
codes, names, grades = np.loadtxt('Datasets/gradebook.csv', delimiter=',', 
                                            skiprows=1, usecols= (2, 3, 4), dtype=str, unpack=True)
for i in range(len(codes)):
        print(f'{codes[i]}: {names[i]}, {grades[i]}')

GBH17538: Le Minh Huong, 6.5
GCH16025: Bui Phuong Nam, 0
GCH16336: Nguyen The Dat, 6.5
GCH16388: Pham Minh Thang, 6.5
GCH16573: Do Duy Tung, 6.5


In [17]:
import csv

with open('Datasets/gradebook.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) # skip header
    for row in reader:
        print(f'{row[2]}: {row[3]}, {row[4]}, {type(row[4])}')

GBH17538: Le Minh Huong, 6.5, <class 'str'>
GCH16025: Bui Phuong Nam, 0, <class 'str'>
GCH16336: Nguyen The Dat, 6.5, <class 'str'>
GCH16388: Pham Minh Thang, 6.5, <class 'str'>
GCH16573: Do Duy Tung, 6.5, <class 'str'>
